@TripAhead.Trips.Api_HostAddress = http://localhost:5011/api/v1

###
# @name Get all trips
GET {{TripAhead.Trips.Api_HostAddress}}/trips
Accept: application/json

###
# @name Add trip
PUT {{TripAhead.Trips.Api_HostAddress}}/trips
Content-Type: application/json

{
  "name": "Bali - Eastern Jam",
  "description": "The paradise for surfers.",
  "startDate": "2023-04-21T18:25:43+01:00",
  "endDate": "2023-04-22T20:25:50+01:00",
  "maxOccupancy": 5,
  "price": 2000
}

### ----------

###
# @name Get all optional items
GET {{TripAhead.Trips.Api_HostAddress}}/optional-items
Accept: application/json

###
# @name Get optional item by id
GET {{TripAhead.Trips.Api_HostAddress}}/optional-items/{id}
Accept: application/json

###
# @name Add optional item - Equipment
PUT {{TripAhead.Trips.Api_HostAddress}}/optional-items
Content-Type: application/json

{
  "name": "Surfboard",
  "description": "Longboard 9'0; Soft; Navy blue;",
  "type": "1" 
}

###
# @name Remove optional item by id
DELETE {{TripAhead.Trips.Api_HostAddress}}/optional-items/{id}
Accept: application/json